#!/bin/bash

# file path
TOP_DIR="$( cd "$( dirname "$BASH_SOURCE" )" && pwd -P )"

# path of directories
BUILD_DIR=${TOP_DIR}/build
EXEC_DIR=${TOP_DIR}/bin

# functions
. ${TOP_DIR}/functions

# pre-install
get_tools
get_dependency

# export
export CC=${GCC_COMPILER}
export CXX=${GXX_COMPILER}

set_directory ${BUILD_DIR}
set_directory ${EXEC_DIR}

cd ${BUILD_DIR}
cmake ..
make -j4
make install
